---
title: "数据重塑"
order: 2
format: live-html
toc: true
webr:
  packages:
    - recipes
    - rsample
    - modeldata
    - themis
    - magrittr
---

## tidymodels

> The tidymodels framework is a collection of packages for modeling and machine learning using tidyverse principles.

tidymodels 系列包提供了数据建模与分析的一整套流程. 主要的包包括:

- recipes: 数据预处理与特征工程
- parsnip: 接口/后端分离的模型指定
- yardstick: 提供各种模型性能指标
- rsample: 基于重采样的模型评估 (如 bootstrap, cross-validation)
- tune: 模型超参数调优
- workflows: 将预处理/建模打包为工作流

### recipes

recipes 包用于以声明式 (declarative) 语法组织数据预处理流程. 其基本思想是将"对数据做什么变换"与"何时真正执行这些变换"分离. 现介绍其基本用法

我们先利用 rsample 包切分出训练集和测试集

```{webr}
library(modeldata)

data("credit_data")

library(rsample)

set.seed(2026)
train_test_split <- initial_split(credit_data)

credit_train <- training(train_test_split)
credit_test <- testing(train_test_split)
```

接下来, 我们基于训练集创建一个 recipe 对象, 并为其添加想要的 step.

```{webr}
credit_rec <- 
    # 创建时用 formula 指定各变量的 role, 也可使用 update_role() 等函数修改
    recipe(Status ~ ., data = credit_train) %>% 
    step_impute_knn(all_predictors()) %>%    # 缺失值填补
    step_dummy(all_nominal_predictors()) %>% # 哑变量生成
    step_center(all_numeric_predictors()) |> # 中心化
    step_scale(all_numeric_predictors())     # 标准化

credit_rec
```

此时我们已经完成了一份菜谱, 其中记录了烹饪的步骤. 接下来, 我们需要为其准备调料, 比如中心化和标准化中需要计算出均值和标准差作为调料.

```{webr}
credit_rec %<>% 
    prep(verbose = TRUE)
```

最后, 我们基于这些烹饪步骤和佐料, 真正对数据进行预处理.

```{webr}
train_data <- 
    bake(credit_rec, new_data = credit_train)

test_data <- 
    bake(credit_rec, new_data = credit_test)
```

之所以要将预处理拆分为 `prep()`/`bake()` 是为了将同一套预处理流程用于多个数据集. 比如, 为了防止测试集信息泄露, 在中心化/标准化时应只使用训练集的均值和标准差, 对测试集预处理时也应使用训练集的归一化参数. 这与 sklearn 中 `fit_transform` 和 `transform` 方法的设计原则类似.

## 特征衍生

recipes 提供了一系列特征工程工具:

- step_poly(): 多项式特征
- step_ns(): 自然样条特征
- step_pca(): 主成分特征
- step_interact(): 生成特征交互项
- ...

这里以 step_poly() 为例, 在 mtcars 数据集中生成 mpg 的二次项:

```{webr}
recipe(mpg ~ ., data = mtcars) %>%
    step_poly(mpg, degree = 2) %>% 
    prep() %>% 
    bake(new_data = NULL) %>% 
    str()
```


## 类别不平衡问题

themis 包对 recipe 包作补充, 提供了一系列处理不平衡数据的 step.

- 过采样
    - step_upsample(): 简单过采样
    - step_smote(): SMOTE 算法
    - step_smotenc(): SMOTENC 算法
    - step_bsmote(): borderline-SMOTE 算法
    - step_adasyn(): ADASYN 算法
    - step_rose(): ROSE 算法

- 欠采样
    - step_downsample(): 简单欠采样
    - step_nearmiss(): NearMiss 算法
    - step_tomek(): Tomek Links 算法

其和 recipes 中的用法完全一致:

```{webr}
library(themis)
library(modeldata)

data(hpc_data)

hpc_data0 <- 
    hpc_data %>%
    select(-protocol, -day) %T>% print()
```

```{webr}
count(hpc_data0, class, name = "orig")
```

```{webr}
recipe(class ~ ., data = hpc_data0) %>%
    step_smote(class, over_ratio = 1000/2211) %>%
    prep() %>%
    bake(new_data = NULL) %>%
    count(class, name = "training")
```